/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_keyboard_keyboarddemo_ndk_JniUtil */

#ifndef _Included_com_keyboard_keyboarddemo_ndk_JniUtil
#define _Included_com_keyboard_keyboarddemo_ndk_JniUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_keyboard_keyboarddemo_ndk_JniUtil
 * Method:    getCLanguageString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_keyboard_keyboarddemo_ndk_JniUtil_getCLanguageString
  (JNIEnv *, jobject);

/*
 * Class:     com_keyboard_keyboarddemo_ndk_JniUtil
 * Method:    getCandidateNum
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_keyboard_keyboarddemo_ndk_JniUtil_getCandidateNum
  (JNIEnv *, jobject);

/*
 * Class:     com_keyboard_keyboarddemo_ndk_JniUtil
 * Method:    getCandidateCount
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_keyboard_keyboarddemo_ndk_JniUtil_getCandidateCount
  (JNIEnv *, jobject);

/*
 * Class:     com_keyboard_keyboarddemo_ndk_JniUtil
 * Method:    InputKey
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_keyboard_keyboarddemo_ndk_JniUtil_InputKey
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_keyboard_keyboarddemo_ndk_JniUtil
 * Method:    initialize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_keyboard_keyboarddemo_ndk_JniUtil_initialize
  (JNIEnv *, jobject);

/*
 * Class:     com_keyboard_keyboarddemo_ndk_JniUtil
 * Method:    getCandidate
 * Signature: (II)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_keyboard_keyboarddemo_ndk_JniUtil_getCandidate
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_keyboard_keyboarddemo_ndk_JniUtil
 * Method:    clearContext
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_keyboard_keyboarddemo_ndk_JniUtil_clearContext
  (JNIEnv *, jobject);

/*
 * Class:     com_keyboard_keyboarddemo_ndk_JniUtil
 * Method:    submitWord
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_keyboard_keyboarddemo_ndk_JniUtil_submitWord
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_keyboard_keyboarddemo_ndk_JniUtil
 * Method:    getComposeString
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_keyboard_keyboarddemo_ndk_JniUtil_getComposeString
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_keyboard_keyboarddemo_ndk_JniUtil
 * Method:    getState
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_keyboard_keyboarddemo_ndk_JniUtil_getState
  (JNIEnv *, jobject);

/*
 * Class:     com_keyboard_keyboarddemo_ndk_JniUtil
 * Method:    getSelectCountNum
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_keyboard_keyboarddemo_ndk_JniUtil_getSelectCountNum
  (JNIEnv *, jobject);

/*
 * Class:     com_keyboard_keyboarddemo_ndk_JniUtil
 * Method:    setAssetsPath
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_keyboard_keyboarddemo_ndk_JniUtil_setAssetsPath
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_keyboard_keyboarddemo_ndk_JniUtil
 * Method:    hwrengine_init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_keyboard_keyboarddemo_ndk_JniUtil_hwrengine_1init
  (JNIEnv *, jobject);

/*
 * Class:     com_keyboard_keyboarddemo_ndk_JniUtil
 * Method:    hwrGetCandidate
 * Signature: (Ljava/util/ArrayList;)Ljava/util/ArrayList;
 */
JNIEXPORT jobject JNICALL Java_com_keyboard_keyboarddemo_ndk_JniUtil_hwrGetCandidate
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
